### PR TITLE
Fixed datatest ids and some renaming

### LINKED ISSUE #12: Fix Create Safe test
Currently the create safe e2e test is not working, this is most probably related to missing selectors

### PR DESCRIPTION
**Pull request by juampibermani**
## What it solves
Resolves #12 

## How this PR fixes it

Changed some data test ids

## How to test it

Run the create safe e2e test using this pr https://github.com/gnosis/safe-react/pull/2503

### CODE REVIEW

File: utils/selectors/createSafePage.js [hunk 1]
```diff
@@ -13,8 +13,8 @@ export const createSafePage = {
   step_three: "p[data-testid='create-safe-step-three']",
   review_safe_name: "p[data-testid='create-safe-review-name']",
   review_req_conf: (ownerAmount = 1) => `p[data-testid='create-safe-review-req-owners-${ownerAmount}']`,
-  review_owner_name: (index = 0) => `p[data-testid='create-safe-owner-name-${index}']`,
-  review_owner_address: (index = 0) => `p[data-testid='create-safe-owner-address-${index}']`,
+  review_owner_name: (index = 0) => `div[data-testid='create-safe-owner-details-${index}'] div div p`,
+  review_owner_address: (index = 0) => `div[data-testid='create-safe-owner-details-${index}'] div div div p`,
```
Comment (katspaugh) [inline utils/selectors/createSafePage.js:17]: Can we skip the nested divs and just target the p?
Like this:
```
div[data-testid='create-safe-owner-details-${index}'] p
```

Comment (juampibermani) [reply utils/selectors/createSafePage.js:17]: We are using those divs as identifiers to select between name and address. If not we would have to add more data-testids.

Comment (katspaugh) [reply utils/selectors/createSafePage.js:17]: Oh, OK, both are in a <p> element. 🆗

**Review by katspaugh — APPROVED** [review]
